### ISSUE TITLE
似乎启动不成功，使用最新的PCRC和PCDR我没有启动成功，PCRC单独使用可以运行，用PCDR会爆出下面的错误，是哪一步有问题吗。'ServerInterface' object has no attribute 'reply'

### ISSUE THREAD

**Issue by TANGhz17** [TISUnion/PCRC-MCDR#3]
!!PCRC start
Exception in thread on_info@PCRC-MCDR:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./plugins/PCRC-MCDR.py", line 18, in on_info
    server.reply(info, 'Starting PCRC')
AttributeError: 'ServerInterface' object has no attribute 'reply'

**Comment by TANGhz17** [comment]
[Server] [23:34:13] [Server thread/INFO]: <TANGhz17> !!PCRC start
Exception in thread on_info@PCRC-MCDR:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./plugins/PCRC-MCDR.py", line 18, in on_info
    server.reply(info, 'Starting PCRC')
AttributeError: 'ServerInterface' object has no attribute 'reply'

[Server] [23:35:10] [Server thread/INFO]: BOT_PCRC[/127.0.0.1:8565] logged in with entity id 1471799 at (89.20105874838907, 154.11243016765727, 470.8602763633888)
[Server] [23:35:10] [Netty Server IO #24/WARN]: Received invalid identifier in minecraft:register: legacy:fml|hs (Non [a-z0-9/._-] character in path of location: legacy:fml|hs)
[Server] [23:35:10] [Server thread/INFO]: BOT_PCRC joined the game
[Server] [23:35:10] [Server thread/INFO]: <BOT_PCRC> o/ 开始录制！

!!PCRC stop
Exception in thread on_info@PCRC-MCDR:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./plugins/PCRC-MCDR.py", line 27, in on_info
    server.reply(info, 'PCRC is not running!')
AttributeError: 'ServerInterface' object has no attribute 'reply'
似乎还是有bug，它没法控制PCRC本体，

**Comment by Sciroccogti** [comment]
你确定使用的是 [MCDReforged](https://github.com/Fallen-Breath/MCDReforged) 吗？

这个报错来看可能是 使用了错误的 MCD。

**Comment by Fallen-Breath** [comment]
MCDR太旧了
